[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/organisations/"
to = "/les-constructeurs-solidaires/"

[[redirects]]
from = "/actualites/2025-01-01-le-studio-pourquoi-pas-la-regie-de-quartier-daubervilliers-et-nour-edde-deviennent-societaires-de-co/"
to = "/actualites/2025-01-01-construire-solidaire-accueille-trois-nouveaux-membres/"

